#!/bin/bash

# ═══════════════════════════════════════════════════════════════
# dfxml_exporter.sh - DFXML Report Exporter
# Part of adamantium v2.6
# ═══════════════════════════════════════════════════════════════
#
# This module generates Digital Forensics XML (DFXML) reports
# compatible with forensic tools like Autopsy, Sleuth Kit, and
# bulk_extractor.
#
# DFXML Specification: https://github.com/dfxml-working-group/dfxml_schema
#
# Usage:
#   source lib/forensic/dfxml_exporter.sh
#   dfxml_init "$output_file"
#   dfxml_add_fileobject "$original" "$clean" "$status"
#   dfxml_finalize
# ═══════════════════════════════════════════════════════════════

# Module version
[[ -z "${DFXML_EXPORTER_VERSION:-}" ]] && readonly DFXML_EXPORTER_VERSION="1.0.0"

# DFXML schema version
[[ -z "${DFXML_SCHEMA_VERSION:-}" ]] && readonly DFXML_SCHEMA_VERSION="1.2.0"

# adamantium namespace
[[ -z "${ADAMANTIUM_NS:-}" ]] && readonly ADAMANTIUM_NS="https://github.com/platinum8300/adamantium/ns/1.0"

# ─────────────────────────────────────────────────────────────
# SESSION VARIABLES
# ─────────────────────────────────────────────────────────────

DFXML_OUTPUT_FILE=""
DFXML_TEMP_FILE=""
DFXML_INITIALIZED=false
DFXML_FILEOBJECT_COUNT=0

# ─────────────────────────────────────────────────────────────
# XML HELPERS
# ─────────────────────────────────────────────────────────────

dfxml_escape_xml() {
    # Escape special XML characters
    local str="$1"

    str="${str//&/&amp;}"
    str="${str//</&lt;}"
    str="${str//>/&gt;}"
    str="${str//\"/&quot;}"
    str="${str//\'/&apos;}"

    echo "$str"
}

dfxml_indent() {
    # Add indentation
    local level="${1:-0}"
    printf '%*s' $((level * 2)) ''
}

# ─────────────────────────────────────────────────────────────
# INITIALIZATION
# ─────────────────────────────────────────────────────────────

dfxml_init() {
    # Initialize DFXML document
    local output_file="$1"

    if [ -z "$output_file" ]; then
        # Generate default filename
        local timestamp
        timestamp=$(date +"%Y%m%d_%H%M%S")
        output_file="${FORENSIC_REPORT_DIR:-$HOME/.adamantium/forensic_reports}/adamantium_${timestamp}.dfxml"
    fi

    DFXML_OUTPUT_FILE="$output_file"
    DFXML_TEMP_FILE=$(mktemp)
    DFXML_INITIALIZED=true
    DFXML_FILEOBJECT_COUNT=0

    # Ensure directory exists
    mkdir -p "$(dirname "$DFXML_OUTPUT_FILE")" 2>/dev/null

    # Write XML header
    cat > "$DFXML_TEMP_FILE" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<dfxml version="${DFXML_SCHEMA_VERSION}"
       xmlns="http://www.forensicswiki.org/wiki/Category:Digital_Forensics_XML"
       xmlns:dc="http://purl.org/dc/elements/1.1/"
       xmlns:adamantium="${ADAMANTIUM_NS}">

EOF

    # Add metadata section
    dfxml_write_metadata

    # Add creator section
    dfxml_write_creator
}

dfxml_write_metadata() {
    # Write DFXML metadata section
    local timestamp
    timestamp=$(forensic_get_timestamp_precise 2>/dev/null || date -u +"%Y-%m-%dT%H:%M:%SZ")

    cat >> "$DFXML_TEMP_FILE" <<EOF
  <!-- Document metadata -->
  <metadata>
    <dc:type>Metadata Cleaning Report</dc:type>
    <dc:creator>adamantium</dc:creator>
    <dc:date>$timestamp</dc:date>
    <dc:description>Metadata cleaning operation report generated by adamantium</dc:description>
  </metadata>

EOF
}

dfxml_write_creator() {
    # Write DFXML creator section with execution environment
    local timestamp hostname os_name os_release os_version arch username uid
    local adamantium_version exiftool_version ffmpeg_version

    timestamp=$(forensic_get_timestamp_precise 2>/dev/null || date -u +"%Y-%m-%dT%H:%M:%SZ")
    hostname=$(hostname 2>/dev/null || echo "unknown")
    os_name=$(uname -s 2>/dev/null || echo "unknown")
    os_release=$(uname -r 2>/dev/null || echo "unknown")
    os_version=$(uname -v 2>/dev/null || echo "unknown")
    arch=$(uname -m 2>/dev/null || echo "unknown")
    username=$(whoami 2>/dev/null || echo "$USER")
    uid=$(id -u 2>/dev/null || echo "unknown")

    adamantium_version="${ADAMANTIUM_VERSION:-unknown}"
    exiftool_version=$(exiftool -ver 2>/dev/null || echo "unknown")
    ffmpeg_version=$(ffmpeg -version 2>/dev/null | head -1 | cut -d' ' -f3 || echo "unknown")

    cat >> "$DFXML_TEMP_FILE" <<EOF
  <!-- Creator information -->
  <creator>
    <program>adamantium</program>
    <version>$adamantium_version</version>
    <execution_environment>
      <os_sysname>$os_name</os_sysname>
      <os_release>$os_release</os_release>
      <os_version>$(dfxml_escape_xml "$os_version")</os_version>
      <host>$hostname</host>
      <arch>$arch</arch>
      <uid>$uid</uid>
      <username>$username</username>
      <start_time>$timestamp</start_time>
    </execution_environment>
    <library name="exiftool" version="$exiftool_version"/>
    <library name="ffmpeg" version="$ffmpeg_version"/>
  </creator>

EOF

    # Add case information if available
    if [ -n "$FORENSIC_CASE_ID" ] || [ -n "$FORENSIC_EVIDENCE_ID" ]; then
        cat >> "$DFXML_TEMP_FILE" <<EOF
  <!-- Case information -->
  <adamantium:case_info>
EOF
        [ -n "$FORENSIC_CASE_ID" ] && echo "    <adamantium:case_id>$FORENSIC_CASE_ID</adamantium:case_id>" >> "$DFXML_TEMP_FILE"
        [ -n "$FORENSIC_EVIDENCE_ID" ] && echo "    <adamantium:evidence_id>$FORENSIC_EVIDENCE_ID</adamantium:evidence_id>" >> "$DFXML_TEMP_FILE"
        echo "    <adamantium:operator>$(forensic_get_operator 2>/dev/null || echo "$USER")</adamantium:operator>" >> "$DFXML_TEMP_FILE"
        echo "    <adamantium:execution_id>${FORENSIC_EXECUTION_ID:-$(cat /proc/sys/kernel/random/uuid 2>/dev/null || date +%s)}</adamantium:execution_id>" >> "$DFXML_TEMP_FILE"
        echo "  </adamantium:case_info>" >> "$DFXML_TEMP_FILE"
        echo "" >> "$DFXML_TEMP_FILE"
    fi
}

# ─────────────────────────────────────────────────────────────
# FILE OBJECT HANDLING
# ─────────────────────────────────────────────────────────────

dfxml_add_fileobject() {
    # Add a fileobject element for a processed file
    local original_file="$1"
    local clean_file="$2"
    local status="${3:-success}"
    local metadata_removed="${4:-0}"

    if [ "$DFXML_INITIALIZED" != "true" ]; then
        echo "Error: DFXML not initialized. Call dfxml_init first." >&2
        return 1
    fi

    if [ ! -f "$original_file" ]; then
        echo "Error: Original file not found: $original_file" >&2
        return 1
    fi

    ((DFXML_FILEOBJECT_COUNT++))

    local filename filesize
    local md5_hash sha1_hash sha256_hash
    local mtime atime ctime
    local clean_size clean_md5 clean_sha1 clean_sha256
    local operation_id timestamp

    filename=$(basename "$original_file")
    filesize=$(stat -c %s "$original_file" 2>/dev/null || stat -f %z "$original_file" 2>/dev/null)

    # Calculate hashes for original file
    md5_hash=$(hash_calculate_md5 "$original_file" 2>/dev/null)
    sha1_hash=$(hash_calculate_sha1 "$original_file" 2>/dev/null)
    sha256_hash=$(hash_calculate_sha256 "$original_file" 2>/dev/null)

    # Get timestamps
    local timestamps
    timestamps=$(forensic_get_file_timestamps "$original_file" 2>/dev/null)
    mtime=$(echo "$timestamps" | grep -o '"mtime": "[^"]*"' | cut -d'"' -f4)
    atime=$(echo "$timestamps" | grep -o '"atime": "[^"]*"' | cut -d'"' -f4)
    ctime=$(echo "$timestamps" | grep -o '"ctime": "[^"]*"' | cut -d'"' -f4)

    # Get clean file info if exists
    if [ -f "$clean_file" ]; then
        clean_size=$(stat -c %s "$clean_file" 2>/dev/null || stat -f %z "$clean_file" 2>/dev/null)
        clean_md5=$(hash_calculate_md5 "$clean_file" 2>/dev/null)
        clean_sha1=$(hash_calculate_sha1 "$clean_file" 2>/dev/null)
        clean_sha256=$(hash_calculate_sha256 "$clean_file" 2>/dev/null)
    fi

    operation_id=$(cat /proc/sys/kernel/random/uuid 2>/dev/null || echo "op-$DFXML_FILEOBJECT_COUNT-$(date +%s)")
    timestamp=$(forensic_get_timestamp_precise 2>/dev/null || date -u +"%Y-%m-%dT%H:%M:%SZ")

    # Write fileobject
    cat >> "$DFXML_TEMP_FILE" <<EOF
  <!-- File object #$DFXML_FILEOBJECT_COUNT -->
  <fileobject>
    <filename>$(dfxml_escape_xml "$filename")</filename>
    <filesize>$filesize</filesize>

    <!-- Hash digests (original file) -->
EOF

    [ -n "$md5_hash" ] && echo "    <hashdigest type=\"md5\">$md5_hash</hashdigest>" >> "$DFXML_TEMP_FILE"
    [ -n "$sha1_hash" ] && echo "    <hashdigest type=\"sha1\">$sha1_hash</hashdigest>" >> "$DFXML_TEMP_FILE"
    [ -n "$sha256_hash" ] && echo "    <hashdigest type=\"sha256\">$sha256_hash</hashdigest>" >> "$DFXML_TEMP_FILE"

    cat >> "$DFXML_TEMP_FILE" <<EOF

    <!-- Timestamps -->
    <mtime>$mtime</mtime>
    <atime>$atime</atime>
    <ctime>$ctime</ctime>

    <!-- adamantium cleaning operation -->
    <adamantium:cleaning_operation>
      <adamantium:operation_id>$operation_id</adamantium:operation_id>
      <adamantium:timestamp>$timestamp</adamantium:timestamp>
      <adamantium:status>$status</adamantium:status>
      <adamantium:metadata_removed_count>$metadata_removed</adamantium:metadata_removed_count>

      <adamantium:original_file>
        <adamantium:path>$(dfxml_escape_xml "$original_file")</adamantium:path>
        <adamantium:size>$filesize</adamantium:size>
        <adamantium:hashdigest type="sha256">$sha256_hash</adamantium:hashdigest>
      </adamantium:original_file>
EOF

    if [ -f "$clean_file" ]; then
        cat >> "$DFXML_TEMP_FILE" <<EOF

      <adamantium:clean_file>
        <adamantium:path>$(dfxml_escape_xml "$clean_file")</adamantium:path>
        <adamantium:size>$clean_size</adamantium:size>
        <adamantium:hashdigest type="sha256">$clean_sha256</adamantium:hashdigest>
      </adamantium:clean_file>
EOF
    fi

    cat >> "$DFXML_TEMP_FILE" <<EOF
    </adamantium:cleaning_operation>
  </fileobject>

EOF
}

# ─────────────────────────────────────────────────────────────
# FINALIZATION
# ─────────────────────────────────────────────────────────────

dfxml_finalize() {
    # Finalize and write DFXML document
    if [ "$DFXML_INITIALIZED" != "true" ]; then
        echo "Error: DFXML not initialized" >&2
        return 1
    fi

    # Add summary
    local end_time
    end_time=$(forensic_get_timestamp_precise 2>/dev/null || date -u +"%Y-%m-%dT%H:%M:%SZ")

    cat >> "$DFXML_TEMP_FILE" <<EOF
  <!-- Summary -->
  <adamantium:summary>
    <adamantium:total_files>$DFXML_FILEOBJECT_COUNT</adamantium:total_files>
    <adamantium:end_time>$end_time</adamantium:end_time>
  </adamantium:summary>

</dfxml>
EOF

    # Move to final location
    mv "$DFXML_TEMP_FILE" "$DFXML_OUTPUT_FILE"

    # Validate if xmllint is available
    if [ "$FORENSIC_VALIDATE_OUTPUT" = "true" ] && command -v xmllint &>/dev/null; then
        if ! xmllint --noout "$DFXML_OUTPUT_FILE" 2>/dev/null; then
            echo "Warning: DFXML validation failed" >&2
        fi
    fi

    DFXML_INITIALIZED=false

    echo "$DFXML_OUTPUT_FILE"
}

dfxml_get_output_file() {
    # Get the output file path
    echo "$DFXML_OUTPUT_FILE"
}

# ─────────────────────────────────────────────────────────────
# VALIDATION
# ─────────────────────────────────────────────────────────────

dfxml_validate() {
    # Validate DFXML file against schema
    local file="${1:-$DFXML_OUTPUT_FILE}"
    local schema="${2:-}"

    if [ ! -f "$file" ]; then
        echo "Error: File not found: $file" >&2
        return 1
    fi

    if ! command -v xmllint &>/dev/null; then
        echo "Warning: xmllint not available, skipping validation" >&2
        return 0
    fi

    # Basic XML validation
    if ! xmllint --noout "$file" 2>/dev/null; then
        echo "Error: XML is not well-formed" >&2
        return 1
    fi

    # Schema validation if schema provided
    if [ -n "$schema" ] && [ -f "$schema" ]; then
        if ! xmllint --schema "$schema" "$file" --noout 2>/dev/null; then
            echo "Error: Schema validation failed" >&2
            return 1
        fi
    fi

    return 0
}

# ─────────────────────────────────────────────────────────────
# MODULE INFO
# ─────────────────────────────────────────────────────────────

dfxml_exporter_info() {
    cat <<EOF
dfxml_exporter.sh v${DFXML_EXPORTER_VERSION}
adamantium DFXML Report Exporter

This module generates Digital Forensics XML (DFXML) reports
compatible with forensic analysis tools.

DFXML Schema Version: $DFXML_SCHEMA_VERSION
adamantium Namespace: $ADAMANTIUM_NS

Compatible tools:
  - Autopsy (import)
  - The Sleuth Kit (fiwalk)
  - bulk_extractor
  - PhotoRec

Features:
  - Execution environment capture
  - Multi-hash support (MD5, SHA1, SHA256)
  - File timestamps (MACB)
  - Cleaning operation details
  - Case and evidence ID tracking

XML validation:
$(command -v xmllint &>/dev/null && echo "  - xmllint: available" || echo "  - xmllint: NOT available (install libxml2)")
EOF
}
